name: tencentVideoAutoCheck
run-name: tencentVideoAutCheck ðŸš€
on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 0 * * *'
    - cron: '0 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tencentVideoAutoCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # ä½¿ç”¨é€‚å½“çš„ Python ç‰ˆæœ¬

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # å®‰è£…ä¾èµ–

      - name: Run check-in-status
        run: |
          python main.py --login_cookie "$LOGIN_COOKIE" --login_url "$LOGIN_URL" --login_url_payload "$LOGIN_URL_PAYLOADLOAD" --PUSHPLUS_TOKEN "$PUSHPLUS_TOKEN" >> run.log
        env:
          LOGIN_COOKIE: ${{ secrets.LOGIN_COOKIE }}
          LOGIN_URL: ${{secrets.LOGIN_URL}}
          LOGIN_URL_PAYLOADLOAD: ${{secrets.LOGIN_URL_PAYLOADLOAD}}
          PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}

      - name: Append Success Log #è¿½åŠ æˆåŠŸæ—¥å¿—
        run: |
          echo "$(date +%Y-%m-%d\ %H:%M:%S) - ç­¾åˆ°æˆåŠŸ" >> run.log
      - name: Upload log #ä¸Šä¼ æ—¥å¿—
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: run.log
      - name: Push log #æ›´æ–°æ—¥å¿—
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto-checkin
          branch: main
